export enum ExperienceType {
  USER_ASKED_IDENTITY = "USER_ASKED_IDENTITY",
  USER_ASKED_RELATIONSHIP = "USER_ASKED_RELATIONSHIP",
  USER_ASKED_ARCON_IDENTITY = "USER_ASKED_ARCON_IDENTITY",
  USER_PRAISED_ARCON = "USER_PRAISED_ARCON",
  USER_ASKED_SELF = "USER_ASKED_SELF",

  // Expanded experience types to support richer personality features
  USER_TESTED_MEMORY = "USER_TESTED_MEMORY",
  USER_CORRECTED_ARCON = "USER_CORRECTED_ARCON",
  USER_SHARED_PREFERENCE = "USER_SHARED_PREFERENCE",
  USER_SHARED_RELATIONSHIP = "USER_SHARED_RELATIONSHIP",
  USER_SHARED_PROJECT = "USER_SHARED_PROJECT",
  USER_ASKED_PROJECT = "USER_ASKED_PROJECT",
  USER_SHOWED_INTEREST = "USER_SHOWED_INTEREST",
  USER_EXPRESSED_FRUSTRATION = "USER_EXPRESSED_FRUSTRATION",
  USER_EXPRESSED_POSITIVE_FEEDBACK = "USER_EXPRESSED_POSITIVE_FEEDBACK",
  USER_CORRECTED_MEMORY = "USER_CORRECTED_MEMORY",
  USER_CONFIRMED_MEMORY = "USER_CONFIRMED_MEMORY",
}
