export enum ExperienceType {
  USER_ASKED_IDENTITY = "USER_ASKED_IDENTITY",
  USER_ASKED_RELATIONSHIP = "USER_ASKED_RELATIONSHIP",
  USER_ASKED_ARCON_IDENTITY = "USER_ASKED_ARCON_IDENTITY",
  USER_PRAISED_ARCON = "USER_PRAISED_ARCON",
  USER_ASKED_SELF = "USER_ASKED_SELF",
}
